#include "CatalogManager.h"
#include "Parser.h"
#include <fstream>
#include <stdexcept>
using namespace std;namespace fs=std::filesystem;static constexpr char SEP='\x1F';
static vector<string> partsOf(const string&line){vector<string>p;string c;for(char x:line){if(x==SEP){p.push_back(c);c.clear();}else c+=x;}p.push_back(c);return p;}
CatalogManager::CatalogManager(fs::path p):catalogDirectory_(std::move(p)){}fs::path CatalogManager::databasesPath()const{return catalogDirectory_/"SystemDatabases.bin";}fs::path CatalogManager::tablesPath()const{return catalogDirectory_/"SystemTables.bin";}fs::path CatalogManager::columnsPath()const{return catalogDirectory_/"SystemColumns.bin";}fs::path CatalogManager::indexesPath()const{return catalogDirectory_/"SystemIndexes.bin";}
void CatalogManager::initialize(){fs::create_directories(catalogDirectory_);ofstream(databasesPath(),ios::binary|ios::app);ofstream(tablesPath(),ios::binary|ios::app);ofstream(columnsPath(),ios::binary|ios::app);ofstream(indexesPath(),ios::binary|ios::app);}
vector<string> CatalogManager::readLines(const fs::path&p){vector<string>o;ifstream f(p,ios::binary);string l;while(getline(f,l))if(!l.empty())o.push_back(l);return o;}void CatalogManager::appendLine(const fs::path&p,const string&l){ofstream f(p,ios::binary|ios::app);if(!f)throw runtime_error("Could not write catalog file: "+p.string());f<<l<<'\n';}
bool CatalogManager::databaseExists(const string&d)const{for(auto&x:readLines(databasesPath()))if(x==d)return true;return false;}void CatalogManager::registerDatabase(const string&d){if(!databaseExists(d))appendLine(databasesPath(),d);}void CatalogManager::registerTable(const string&d,const string&t,const vector<ColumnDefinition>&cs){appendLine(tablesPath(),d+SEP+t);for(auto&c:cs)appendLine(columnsPath(),d+SEP+t+SEP+c.name+SEP+c.type+SEP+to_string(c.varcharLength)+SEP+(c.nullable?"1":"0"));}
void CatalogManager::unregisterTable(const string&d,const string&t){auto rw=[&](const fs::path&p){vector<string>keep;for(auto&l:readLines(p)){auto x=partsOf(l);if(!(x.size()>=2&&x[0]==d&&x[1]==t))keep.push_back(l);}ofstream f(p,ios::binary|ios::trunc);for(auto&l:keep)f<<l<<'\n';};rw(tablesPath());rw(columnsPath());rw(indexesPath());}
void CatalogManager::registerIndex(const IndexMetadata&m){for(auto&i:allIndexes())if(i.name==m.name)throw runtime_error("Index already exists: "+m.name);appendLine(indexesPath(),m.database+SEP+m.table+SEP+m.name+SEP+m.column+SEP+m.type);}
vector<IndexMetadata> CatalogManager::allIndexes()const{vector<IndexMetadata>o;for(auto&l:readLines(indexesPath())){auto p=partsOf(l);if(p.size()>=5)o.push_back({p[0],p[1],p[2],p[3],p[4]});}return o;}vector<IndexMetadata> CatalogManager::indexesForTable(const string&d,const string&t)const{vector<IndexMetadata>o;for(auto&i:allIndexes())if(i.database==d&&i.table==t)o.push_back(i);return o;}bool CatalogManager::indexedColumnExists(const string&d,const string&t,const string&c)const{for(auto&i:indexesForTable(d,t))if(i.column==c)return true;return false;}
vector<map<string,string>> CatalogManager::selectSystemTable(const string&name)const{string n=Parser::upper(name);vector<map<string,string>>o;if(n=="SYSTEMDATABASES"){for(auto&l:readLines(databasesPath()))o.push_back({{"Database",l}});}else if(n=="SYSTEMTABLES"){for(auto&l:readLines(tablesPath())){auto p=partsOf(l);if(p.size()>=2)o.push_back({{"Database",p[0]},{"Table",p[1]}});}}else if(n=="SYSTEMCOLUMNS"){for(auto&l:readLines(columnsPath())){auto p=partsOf(l);if(p.size()>=4)o.push_back({{"Database",p[0]},{"Table",p[1]},{"Column",p[2]},{"Type",p[3]}});}}else if(n=="SYSTEMINDEXES"){for(auto&i:allIndexes())o.push_back({{"Database",i.database},{"Table",i.table},{"Index",i.name},{"Column",i.column},{"Type",i.type}});}else throw runtime_error("Unknown system catalog table: "+name);return o;}
