#include "StoredDataManager.h"
#include "Validator.h"
#include <algorithm>
#include <chrono>
#include <filesystem>
#include <set>
#include <stdexcept>
using namespace std;namespace fs=std::filesystem;
StoredDataManager::StoredDataManager(fs::path root):rootDirectory_(std::move(root)),catalog_(rootDirectory_/"catalog"){fs::create_directories(rootDirectory_);catalog_.initialize();for(auto&i:catalog_.allIndexes()){try{rebuildIndex(i);}catch(...){}}}
fs::path StoredDataManager::databasePath(const string&d)const{return rootDirectory_/d;}fs::path StoredDataManager::tablePath(const string&d,const string&t)const{return databasePath(d)/t;}TableFile StoredDataManager::tableFile(const string&d,const string&t)const{return TableFile(tablePath(d,t));}string StoredDataManager::indexKey(const string&d,const string&t){return d+"\x1F"+t;}
bool StoredDataManager::databaseExists(const string&d)const{return catalog_.databaseExists(d);}void StoredDataManager::createDatabase(const string&d){Validator::validateDatabaseName(d);if(databaseExists(d))throw runtime_error("Database already exists: "+d);if(!fs::create_directories(databasePath(d)))throw runtime_error("Could not create database directory: "+databasePath(d).string());catalog_.registerDatabase(d);}
void StoredDataManager::createTable(const string&d,const string&t,const vector<ColumnDefinition>&c){if(!databaseExists(d))throw runtime_error("Database does not exist: "+d);Validator::validateTableName(t);Validator::validateColumnDefinitions(c);auto tf=tableFile(d,t);if(tf.exists())throw runtime_error("Table already exists: "+t);tf.create({t,c});catalog_.registerTable(d,t,c);}
void StoredDataManager::dropTable(const string&d,const string&t){auto tf=tableFile(d,t);if(!tf.exists())throw runtime_error("Table does not exist: "+t);if(!tf.isEmpty())throw runtime_error("Cannot drop table '"+t+"' because it contains rows");tf.removeFiles();catalog_.unregisterTable(d,t);indexes_.erase(indexKey(d,t));}
void StoredDataManager::indexInsert(RuntimeIndex&i,const string&k,long p){if(i.bst)i.bst->insert(k,p);else i.btree->insert(k,p);}long StoredDataManager::indexFind(const RuntimeIndex&i,const string&k)const{return i.bst?i.bst->find(k):i.btree->find(k);}
void StoredDataManager::rebuildIndex(const IndexMetadata&m){auto tf=tableFile(m.database,m.table);if(!tf.exists())throw runtime_error("Cannot rebuild index '"+m.name+"': table does not exist");RuntimeIndex r;r.meta=m;auto rows=tf.readRowsWithOffsets();if(m.type=="BST"){r.bst=make_shared<BSTIndex>();vector<pair<string,long>> entries;entries.reserve(rows.size());for(auto&[off,row]:rows)entries.push_back({row.at(m.column),off});sort(entries.begin(),entries.end(),[](const auto&a,const auto&b){return a.first<b.first;});r.bst->buildFromSorted(entries);}else{r.btree=make_shared<BTreeIndex>();for(auto&[off,row]:rows)r.btree->insert(row.at(m.column),off);}indexes_[indexKey(m.database,m.table)]=std::move(r);}
void StoredDataManager::rebuildIndexesForTable(const string&d,const string&t){for(auto&m:catalog_.indexesForTable(d,t))rebuildIndex(m);}
void StoredDataManager::insertRow(const string&d,const string&t,const vector<string>&values){auto tf=tableFile(d,t);if(!tf.exists())throw runtime_error("Table does not exist: "+t);auto schema=tf.readSchema();Validator::validateInsertValues(schema,values);Row row;for(size_t i=0;i<schema.columns.size();++i)row[schema.columns[i].name]=values[i];auto key=indexKey(d,t);auto it=indexes_.find(key);if(it!=indexes_.end()){string v=row.at(it->second.meta.column);if((it->second.bst&&it->second.bst->contains(v))||(it->second.btree&&it->second.btree->contains(v)))throw runtime_error("Duplicate value '"+v+"' violates index '"+it->second.meta.name+"'");}long off=tf.appendRow(schema,row);if(it!=indexes_.end())indexInsert(it->second,row.at(it->second.meta.column),off);}
void StoredDataManager::insertRows(const string&d,const string&t,const vector<vector<string>>&allValues){auto tf=tableFile(d,t);if(!tf.exists())throw runtime_error("Table does not exist: "+t);auto schema=tf.readSchema();vector<Row> rows;rows.reserve(allValues.size());set<string>batchKeys;auto key=indexKey(d,t);auto it=indexes_.find(key);for(const auto&values:allValues){Validator::validateInsertValues(schema,values);Row row;for(size_t i=0;i<schema.columns.size();++i)row[schema.columns[i].name]=values[i];if(it!=indexes_.end()){string v=row.at(it->second.meta.column);bool exists=(it->second.bst&&it->second.bst->contains(v))||(it->second.btree&&it->second.btree->contains(v));if(exists||!batchKeys.insert(v).second)throw runtime_error("Duplicate value '"+v+"' violates index '"+it->second.meta.name+"'");}rows.push_back(std::move(row));}auto offsets=tf.appendRows(schema,rows);if(it!=indexes_.end())for(size_t i=0;i<rows.size();++i)indexInsert(it->second,rows[i].at(it->second.meta.column),offsets[i]);}
static string typeFor(const TableSchema&s,const string&c){for(auto&x:s.columns)if(x.name==c)return x.type;throw runtime_error("Column does not exist: "+c);}
int StoredDataManager::compareTyped(const string&a,const string&b,const string&type){string t=Parser::upper(type);if(t=="INTEGER"){long long x=stoll(a),y=stoll(b);return x==y?0:(x<y?-1:1);}if(t=="DOUBLE"){double x=stod(a),y=stod(b);return x==y?0:(x<y?-1:1);}return a==b?0:(a<b?-1:1);}
bool StoredDataManager::matchesWhere(const Row&r,const WhereClause&w,const TableSchema&s){if(!w.enabled)return true;auto it=r.find(w.column);if(it==r.end())throw runtime_error("WHERE column does not exist: "+w.column);int cmp=compareTyped(it->second,w.value,typeFor(s,w.column));if(w.op=="=")return cmp==0;if(w.op==">")return cmp>0;if(w.op=="<")return cmp<0;if(w.op=="NOT")return cmp!=0;if(w.op=="LIKE"){string p=w.value;bool start=!p.empty()&&p.front()=='*',end=!p.empty()&&p.back()=='*';p.erase(remove(p.begin(),p.end(),'*'),p.end());if(start&&end)return it->second.find(p)!=string::npos;if(start)return it->second.size()>=p.size()&&it->second.compare(it->second.size()-p.size(),p.size(),p)==0;if(end)return it->second.rfind(p,0)==0;return it->second==p;}throw runtime_error("Unsupported WHERE operator: "+w.op);}
void StoredDataManager::quickSort(vector<Row>&a,int lo,int hi,const string&c,bool desc,const TableSchema&s){if(lo>=hi)return;string pivot=a[(lo+hi)/2].at(c);int i=lo,j=hi;while(i<=j){auto before=[&](const string&x,const string&y){int z=compareTyped(x,y,typeFor(s,c));return desc?z>0:z<0;};while(before(a[i].at(c),pivot))++i;while(before(pivot,a[j].at(c)))--j;if(i<=j){swap(a[i],a[j]);++i;--j;}}if(lo<j)quickSort(a,lo,j,c,desc,s);if(i<hi)quickSort(a,i,hi,c,desc,s);}
nlohmann::json StoredDataManager::selectRows(const string&d,const ParsedSelect&q){string up=Parser::upper(q.tableName);if(up.rfind("SYSTEM",0)==0){auto src=catalog_.selectSystemTable(q.tableName);nlohmann::json result;vector<string>cols;if(!src.empty())for(auto&[k,v]:src[0])cols.push_back(k);result["columns"]=cols;result["rows"]=nlohmann::json::array();for(auto&r:src){nlohmann::json j;for(auto&[k,v]:r)j[k]=v;result["rows"].push_back(j);}result["message"]="System catalog query completed";return result;}
 auto tf=tableFile(d,q.tableName);if(!tf.exists())throw runtime_error("Table does not exist: "+q.tableName);auto schema=tf.readSchema();if(q.where.enabled){Validator::validateColumnExists(schema,q.where.column);Validator::validateValueForType(typeFor(schema,q.where.column),q.where.value);}if(!q.orderByColumn.empty())Validator::validateColumnExists(schema,q.orderByColumn);vector<string>cols;if(q.columns.size()==1&&q.columns[0]=="*")for(auto&c:schema.columns)cols.push_back(c.name);else{cols=q.columns;for(auto&c:cols)Validator::validateColumnExists(schema,c);}vector<Row>filtered;bool usedIndex=false;auto it=indexes_.find(indexKey(d,q.tableName));if(q.where.enabled&&q.where.op=="="&&it!=indexes_.end()&&it->second.meta.column==q.where.column){usedIndex=true;bool has=(it->second.bst&&it->second.bst->contains(q.where.value))||(it->second.btree&&it->second.btree->contains(q.where.value));if(has)filtered.push_back(tf.readRowAt(indexFind(it->second,q.where.value)));}else for(auto&row:tf.readRows())if(matchesWhere(row,q.where,schema))filtered.push_back(row);if(!q.orderByColumn.empty()&&!filtered.empty())quickSort(filtered,0,(int)filtered.size()-1,q.orderByColumn,q.orderDescending,schema);nlohmann::json result;result["columns"]=cols;result["rows"]=nlohmann::json::array();for(auto&r:filtered){nlohmann::json j;for(auto&c:cols)j[c]=r.at(c);result["rows"].push_back(j);}result["message"]=usedIndex?("SELECT used "+it->second.meta.type+" index '"+it->second.meta.name+"'"):"SELECT used sequential scan";return result;}
int StoredDataManager::deleteRows(const string&d,const string&t,const WhereClause&w){auto tf=tableFile(d,t);if(!tf.exists())throw runtime_error("Table does not exist: "+t);auto s=tf.readSchema();if(w.enabled){Validator::validateColumnExists(s,w.column);Validator::validateValueForType(typeFor(s,w.column),w.value);}vector<Row>keep;int n=0;for(auto&r:tf.readRows()){if(matchesWhere(r,w,s))++n;else keep.push_back(r);}tf.writeRows(s,keep);rebuildIndexesForTable(d,t);return n;}
int StoredDataManager::updateRows(const string&d,const ParsedUpdate&u){auto tf=tableFile(d,u.tableName);if(!tf.exists())throw runtime_error("Table does not exist: "+u.tableName);auto s=tf.readSchema();Validator::validateColumnExists(s,u.column);Validator::validateValueForType(typeFor(s,u.column),u.value);if(u.where.enabled){Validator::validateColumnExists(s,u.where.column);Validator::validateValueForType(typeFor(s,u.where.column),u.where.value);}auto rows=tf.readRows();int n=0;for(auto&r:rows)if(matchesWhere(r,u.where,s)){r[u.column]=u.value;++n;}auto metas=catalog_.indexesForTable(d,u.tableName);for(auto&m:metas)if(m.column==u.column){set<string>seen;for(auto&r:rows)if(!seen.insert(r.at(m.column)).second)throw runtime_error("UPDATE would create duplicate value '"+r.at(m.column)+"' in indexed column "+m.column);}tf.writeRows(s,rows);rebuildIndexesForTable(d,u.tableName);return n;}
void StoredDataManager::createIndex(const string&d,const string&name,const string&t,const string&c,const string&type){auto tf=tableFile(d,t);if(!tf.exists())throw runtime_error("Table does not exist: "+t);auto s=tf.readSchema();Validator::validateColumnExists(s,c);if(!catalog_.indexesForTable(d,t).empty())throw runtime_error("Table '"+t+"' already has an index. Only one index per table is allowed");set<string>seen;for(auto&r:tf.readRows())if(!seen.insert(r.at(c)).second)throw runtime_error("Cannot create index. Duplicate value found in column "+c+": "+r.at(c));IndexMetadata m{d,t,name,c,Parser::upper(type)};catalog_.registerIndex(m);rebuildIndex(m);}
