#include "TableFile.h"
#include <fstream>
#include <stdexcept>
using namespace std; namespace fs=std::filesystem; static constexpr char SEP='\x1F'; static constexpr unsigned char KEY=0xA7;
TableFile::TableFile(fs::path p):tableDirectory_(std::move(p)){} fs::path TableFile::schemaPath()const{return tableDirectory_/"schema.bin";} fs::path TableFile::rowsPath()const{return tableDirectory_/"rows.bin";} bool TableFile::exists()const{return fs::exists(schemaPath());}
void TableFile::crypt(string&d){for(char&c:d)c=static_cast<char>(static_cast<unsigned char>(c)^KEY);}
void TableFile::create(const TableSchema&s){fs::create_directories(tableDirectory_);ostringstream plain;plain<<s.tableName<<'\n';for(auto&c:s.columns)plain<<c.name<<SEP<<c.type<<SEP<<c.varcharLength<<SEP<<(c.nullable?1:0)<<'\n';string d=plain.str();crypt(d);ofstream f(schemaPath(),ios::binary|ios::trunc);if(!f)throw runtime_error("Could not create schema file: "+schemaPath().string());f.write(d.data(),d.size());ofstream r(rowsPath(),ios::binary|ios::trunc);if(!r)throw runtime_error("Could not create rows file: "+rowsPath().string());}
TableSchema TableFile::readSchema()const{ifstream f(schemaPath(),ios::binary);if(!f)throw runtime_error("Table schema file does not exist: "+schemaPath().string());string d((istreambuf_iterator<char>(f)),{});crypt(d);istringstream in(d);TableSchema s;getline(in,s.tableName);string line;while(getline(in,line)){vector<string>p;string cur;for(char c:line){if(c==SEP){p.push_back(cur);cur.clear();}else cur+=c;}p.push_back(cur);if(p.size()>=4)s.columns.push_back({p[0],p[1],stoi(p[2]),p[3]=="1"});}return s;}
string TableFile::encodeRow(const TableSchema&s,const Row&r){string o;for(size_t i=0;i<s.columns.size();++i){if(i)o+=SEP;auto it=r.find(s.columns[i].name);o+=it==r.end()?"":it->second;}return o;}
Row TableFile::decodeRow(const TableSchema&s,const string&e){vector<string>v;string cur;for(char c:e){if(c==SEP){v.push_back(cur);cur.clear();}else cur+=c;}v.push_back(cur);Row r;for(size_t i=0;i<s.columns.size();++i)r[s.columns[i].name]=i<v.size()?v[i]:"";return r;}
vector<pair<long,Row>> TableFile::readRowsWithOffsets()const{TableSchema s=readSchema();vector<pair<long,Row>> out;ifstream f(rowsPath(),ios::binary);if(!f)return out;while(true){long off=(long)f.tellg();uint32_t len=0;if(!f.read(reinterpret_cast<char*>(&len),sizeof len))break;if(len>64*1024*1024)throw runtime_error("Corrupted row length in "+rowsPath().string());string d(len,'\0');if(!f.read(d.data(),len))throw runtime_error("Corrupted row data in "+rowsPath().string());crypt(d);out.push_back({off,decodeRow(s,d)});}return out;}
vector<Row> TableFile::readRows()const{vector<Row>r;for(auto&x:readRowsWithOffsets())r.push_back(std::move(x.second));return r;}
Row TableFile::readRowAt(long offset)const{TableSchema s=readSchema();ifstream f(rowsPath(),ios::binary);if(!f)throw runtime_error("Could not open rows file");f.seekg(offset);uint32_t len=0;if(!f.read(reinterpret_cast<char*>(&len),sizeof len))throw runtime_error("Invalid index offset");string d(len,'\0');if(!f.read(d.data(),len))throw runtime_error("Could not read indexed row");crypt(d);return decodeRow(s,d);}
void TableFile::writeRows(const TableSchema&s,const vector<Row>&rows){ofstream f(rowsPath(),ios::binary|ios::trunc);if(!f)throw runtime_error("Could not write rows file");for(auto&r:rows){string d=encodeRow(s,r);crypt(d);uint32_t len=(uint32_t)d.size();f.write(reinterpret_cast<const char*>(&len),sizeof len);f.write(d.data(),len);}}
long TableFile::appendRow(const TableSchema&s,const Row&r){ofstream f(rowsPath(),ios::binary|ios::app);if(!f)throw runtime_error("Could not append row");long off=(long)f.tellp();string d=encodeRow(s,r);crypt(d);uint32_t len=(uint32_t)d.size();f.write(reinterpret_cast<const char*>(&len),sizeof len);f.write(d.data(),len);if(!f)throw runtime_error("Failed while writing row");return off;}

vector<long> TableFile::appendRows(const TableSchema&s,const vector<Row>&rows){ofstream f(rowsPath(),ios::binary|ios::app);if(!f)throw runtime_error("Could not append rows");vector<long> offsets;offsets.reserve(rows.size());for(auto&r:rows){offsets.push_back((long)f.tellp());string d=encodeRow(s,r);crypt(d);uint32_t len=(uint32_t)d.size();f.write(reinterpret_cast<const char*>(&len),sizeof len);f.write(d.data(),len);}if(!f)throw runtime_error("Failed while writing rows");return offsets;}
bool TableFile::isEmpty()const{return readRowsWithOffsets().empty();}void TableFile::removeFiles(){if(fs::exists(tableDirectory_))fs::remove_all(tableDirectory_);}
